aplicaciones/administrador/urls.py
from django.urls import path

from .views.cesta.views import CestaListView, CestaDeleteView, CestaFacturaPdfView
from .views.categoria.views import *
from .views.clientes.views import ClienteCreateView, ClienteUpdateView, ClienteDeleteView, ClienteListView, \
    ClienteSuperCreateView, ClienteSuperUpdateView
from .views.favoritos.views import FavoritosListView, FavoritosDeleteView, FavoritosCestaCreateView
from .views.gestiona_favoritos.views import GestionaFavoritosListView
from .views.importar_csv.views import ImportarCSVListView, ImportarCSVUpdateView, ImportarCSVDeleteView
from .views.muestra_oferta.views import MuestraOfertasListView
from .views.gestiona.views import GestionaProductosListView, GestionaProductosUpdateView, GestionaProductosDeleteView, \
    GestionaProductosCreateView
from .views.ofertas.views import OfertaUpdateView, OfertaCreateView, OfertaListView, OfertaDeleteView
from .views.productos.views import ProductoListView, ProductoCreateView, ProductoUpdateView, ProductoDeleteView
from .views.subcategoria.views import SubCategoriaFormView, SubCategoriaDeleteView, SubCategoriaUpdateView, \
    SubCategoriaCreateView, SubCategoriaListView
from .views.super.views import SuperListView  # , PruebaListView,
from .views.test.views import TestView
from aplicaciones.administrador.views.panelcontrol.views import *
from aplicaciones.administrador.views.ventas.views import VentaListView, VentaCreateView, VentaDeleteView, \
    VentaUpdateView, VentaFacturaPdfView

app_name = 'administrador'

urlpatterns = [
    # categoria
    path('categoria/lista/', CategoriaListView.as_view(), name='categoria_lista'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria_crear'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_editar'),
    path('categoria/eliminar/<int:pk>/', CategoriaDeleteView.as_view(), name='categoria_eliminar'),
    path('categoria/form/', CategoriaFormView.as_view(), name='categoria_form'),
    # subcategoria
    path('subcategoria/lista/', SubCategoriaListView.as_view(), name='subcategoria_lista'),
    path('subcategoria/crear/', SubCategoriaCreateView.as_view(), name='subcategoria_crear'),
    path('subcategoria/editar/<int:pk>/', SubCategoriaUpdateView.as_view(), name='subcategoria_editar'),
    path('subcategoria/eliminar/<int:pk>/', SubCategoriaDeleteView.as_view(), name='subcategoria_eliminar'),
    path('subcategoria/form/', SubCategoriaFormView.as_view(), name='subcategoria_form'),
    # clientes
    path('cliente/lista/', ClienteListView.as_view(), name='cliente_lista'),
    path('cliente/crear/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('cliente/editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editar'),
    path('cliente/eliminar/<int:pk>/', ClienteDeleteView.as_view(), name='cliente_eliminar'),
    path('cliente/crearperfil/', ClienteSuperCreateView.as_view(), name='cliente_crearSuper'),
    path('cliente/editarperfil/<int:pk>/', ClienteSuperUpdateView.as_view(), name='cliente_editarSuper'),
    # productos
    path('producto/lista/', ProductoListView.as_view(), name='producto_lista'),
    path('producto/crear/', ProductoCreateView.as_view(), name='producto_crear'),
    path('producto/editar/<int:pk>/', ProductoUpdateView.as_view(), name='producto_editar'),
    path('producto/eliminar/<int:pk>/', ProductoDeleteView.as_view(), name='producto_eliminar'),
    # oferta
    path('oferta/lista/', OfertaListView.as_view(), name='oferta_lista'),
    path('oferta/crear/', OfertaCreateView.as_view(), name='oferta_crear'),
    path('oferta/editar/<int:pk>/', OfertaUpdateView.as_view(), name='oferta_editar'),
    path('oferta/eliminar/<int:pk>/', OfertaDeleteView.as_view(), name='oferta_eliminar'),
    # ventas
    path('ventas/lista/', VentaListView.as_view(), name='venta_lista'),
    path('ventas/crear/', VentaCreateView.as_view(), name='venta_crear'),
    path('ventas/editar/<int:pk>/', VentaUpdateView.as_view(), name='venta_editar'),
    path('ventas/eliminar/<int:pk>/', VentaDeleteView.as_view(), name='venta_eliminar'),
    path('ventas/factura/pdf/<int:pk>/', VentaFacturaPdfView.as_view(), name='venta_factura'),
    # Super tienda
    path('super/lista/', SuperListView.as_view(), name='super_lista'),
    path('super/lista/<str:pk>/', SuperListView.as_view(), name='super_lista_id'),
    # Cesta tienda
    path('cesta/lista/', CestaListView.as_view(), name='cesta_lista'),
    path('cesta/eliminar/<int:pk>/', CestaDeleteView.as_view(), name='cesta_eliminar'),
    path('cesta/factura/pdf/<int:pk>/', CestaFacturaPdfView.as_view(), name='cesta_factura'),
    # muestra oferta
    path('muestraoferta/lista/', MuestraOfertasListView.as_view(), name='muestra_oferta_lista'),
    # favoritos
    path('favoritos/lista/', FavoritosListView.as_view(), name='favoritos_lista'),
    path('favoritos/eliminar/<int:pk>/', FavoritosDeleteView.as_view(), name='favoritos_eliminar'),
    path('favoritos/agregar_cesta/<int:pk>/', FavoritosCestaCreateView.as_view(), name='favoritos_agregar'),
    # gestiona favoritos
    path('gestiona_favoritos/lista/', GestionaFavoritosListView.as_view(), name='gestiona_favoritosLista'),
    # gestiona productos
    path('gestiona/lista/', GestionaProductosListView.as_view(), name='gestiona_lista'),
    path('gestiona/crear/', GestionaProductosCreateView.as_view(), name='gestiona_crear'),
    path('gestiona/editar/<int:pk>/', GestionaProductosUpdateView.as_view(), name='gestiona_editar'),
    path('gestiona/eliminar/<int:pk>/', GestionaProductosDeleteView.as_view(), name='gestiona_eliminar'),
    # Importar CSV
    path('importar/lista/', ImportarCSVListView.as_view(), name='importar_lista'),
    path('importar/editar/<int:pk>/', ImportarCSVUpdateView.as_view(), name='importar_editar'),
    path('importar/eliminar/<int:pk>/', ImportarCSVDeleteView.as_view(), name='importar_eliminar'),
    # inicio
    path('panelcontrol/', PanelControlView.as_view(), name='panel_control'),
    # test
    path('test/', TestView.as_view(), name='test'),
]

aplicaciones/login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from aplicaciones.login.views import *

app_name = 'perfil'

urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password/', ReseteoPassWordView.as_view(), name='reset_contraseña'),
    path('change/password/<str:token>/', CambiarPassWordView.as_view(), name='change_contraseña')
    # path('logout/', LogoutRedirectView.as_view(), name='logout')
]

configuracion/urls.py
"""configuracion URL Configuration

The `urlpatterns` list routes URLs to oferta. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function oferta
    1. Add an import:  from my_app import oferta
    2. Add a URL to urlpatterns:  path('', oferta.home, name='home')
Class-based oferta
    1. Add an import:  from other_app.oferta import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from aplicaciones.paginainicio.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='inicio'),                                        # página de inicio
    path('adm/', include('aplicaciones.administrador.urls')),                            # llama a tienda
    path('login/', include('aplicaciones.login.urls')),
    path('reporte/', include('aplicaciones.reportes.urls')),
    path('usuario/', include('aplicaciones.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/administrador/views/super/views.py
from django.db import transaction
from django.db.models.functions import Coalesce
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from aplicaciones.administrador.models import Producto, Categoria, SubCategoria, Cesta, Favoritos, DetVenta
from datetime import datetime
from django.db.models import Sum, DecimalField


class SuperListView(ListView):
    template_name = 'super/lista.html'
    model = Producto

    def get_queryset(self):
        # devuelve los productos filtrados por categorías y subcategorías
        if 'pk' in self.kwargs:
            var = self.kwargs['pk']
            if var.isnumeric():
                return Producto.objects.filter(cat_id=var).filter(activo=True)
            elif not var.isnumeric():
                subcate_id = SubCategoria.objects.filter(nombre=var).values('id')
                var_subcat_id = ''
                for i in subcate_id:
                    var_subcat_id = i['id']
                return Producto.objects.filter(subcat_id=var_subcat_id).filter(activo=True)

        # esta parte se encarga del buscador
        query = self.request.GET.get('buscarProductoSuper')
        if query:
            object_list = self.model.objects.filter(nombre__icontains=query).filter(activo=True)
            return object_list
        else:
            object_list = self.model.objects.all()[0:12]
            return object_list

    # calcula la cuenta total
    def calcula_total(self):
        id_cliente = self.request.user.id
        var_total = 0
        total = 0
        for i in Cesta.objects.filter(id_cliente=id_cliente).filter(id_producto__activo=True):
            diccionario = i.toJSON()
            precio = diccionario['id_producto'].get('pvp')
            cant = diccionario['cant']
            cuartos = diccionario['cuartos']
            if cuartos is None:
                cuartos = int(1)
            elif cuartos == '':
                cuartos = int(1)
            elif cuartos == 'cuarto':
                cuartos = float(0.25)
            elif cuartos == 'medio':
                cuartos = float(0.50)
            elif cuartos == 'unidad':
                cuartos = int(1)
            subtotal_fila = (float(precio) * int(cant))*cuartos
            subtotal = round(subtotal_fila, 2)
            var_total += subtotal
            total = var_total
        return "{0:.2f}".format(total)

    # Calcula los productos más vendidos
    def ventas_productos(self):
        data = []
        year = datetime.now().year
        month = datetime.now().month
        try:
            for p in Producto.objects.all():
                total = DetVenta.objects.filter(venta__date_joined__year=year, venta__date_joined__month=month, prod__id=p.id).aggregate(
                    r=Coalesce(Sum('subtotal'), 0, output_field=DecimalField())).get('r')
                if total > 0:
                    data.append({
                        'codigo': p.codigo,
                        'nombre': p.nombre,
                        'cat': p.cat.nombre,
                        'subcat': p.subcat.nombre,
                        'total': float(total)
                    })
        except:
            pass
        return data

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            id_cliente = request.user.id
            if action == 'autocomplete':
                data = []
                for i in Producto.objects.filter(nombre__contains=request.POST['term']).filter(activo=True):
                    item = i.toJSON()
                    item['value'] = i.nombre
                    data.append(item)
            elif action == 'mirar_producto':
                print(request.POST)
                if request.POST:
                    data = []
                    productos = Producto.objects.filter(id=request.POST.get('id'))  # obtiene el objeto producto
                    for i in productos:  # itera y guarda en la variable data
                        item = i.toJSON()
                        print(item)
                        data.append(item)
            elif action == 'busca_id':
                id_producto = request.POST['id']
                comprueba = Cesta.objects.filter(id_cliente=id_cliente).filter(id_producto=id_producto)
                if comprueba:  # si el producto existe
                    comprueba_cant = Cesta.objects.filter(id_cliente=id_cliente).filter(id_producto_id=id_producto).values('cant')
                    cant = 0
                    for i in comprueba_cant:
                        cant = i['cant']
                        cant += 1
                    Cesta.objects.filter(id_cliente=id_cliente).filter(id_producto=id_producto).update(cant=cant)
                else:
                    with transaction.atomic():
                        ces = Cesta()
                        ces.id_cliente = id_cliente
                        ces.id_producto_id = id_producto
                        ces.cuartos = ''
                        comp_cuarto = Producto.objects.filter(id=id_producto).filter(cuartos=True)
                        if comp_cuarto:
                            ces.cuartos = 'unidad'
                            ces.cuartos_checkbox = True
                        ces.cant = 1
                        ces.save()
            elif action == 'borra_prod':
                Cesta.objects.filter(id_cliente=self.request.user.id).filter(id=request.POST['id']).delete()
            elif action == 'añadir_favoritos':
                id_producto = request.POST['id']
                comprueba = Favoritos.objects.filter(id_cliente=id_cliente).filter(id_producto=id_producto)
                if not comprueba:
                    with transaction.atomic():
                        fav = Favoritos()
                        fav.id_producto_id = id_producto
                        fav.id_cliente_id = id_cliente
                        fav.save()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)  # con safe=False para serializarlo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'famisuper'
        context['categorias'] = Categoria.objects.all()
        context['subcategorias'] = SubCategoria.objects.all()
        context['ofertas'] = Producto.objects.filter(oferta_checkbox=True)[0:3]
        context['lista_favoritos'] = self.ventas_productos()
        # añade la cantidad total de productos
        cant_dic = Cesta.objects.filter(id_cliente=self.request.user.id).values('cant')
        cant = 0
        for i in cant_dic:
            cant = cant + i['cant']
        context['cantidad'] = cant
        # añade el total de cuenta, total del producto y los datos de los productos de la cesta en el modal barra
        client = self.request.user.id
        data = []
        for i in Cesta.objects.filter(id_cliente=client).filter(id_producto__activo=True):
            datos = {}
            diccionario = i.toJSON()
            datos['id'] = diccionario['id']
            datos['imagen'] = diccionario['id_producto'].get('imagen')
            datos['nombre'] = diccionario['id_producto'].get('nombre')
            datos['id_cliente'] = diccionario['id_cliente']
            datos['pvp'] = diccionario['id_producto'].get('pvp')
            datos['cant'] = diccionario['cant']
            datos['cuartos'] = diccionario['cuartos']
            cuartos = diccionario['cuartos']
            if cuartos is None:
                cuartos = int(1)
            elif cuartos == '':
                print('None')
                cuartos = int(1)
            elif cuartos == 'cuarto':
                cuartos = float(0.25)
            elif cuartos == 'medio':
                cuartos = float(0.50)
            elif cuartos == 'unidad':
                cuartos = int(1)
            precio = diccionario['id_producto'].get('pvp')
            cantidad = diccionario['cant']
            subtotal = (float(precio) * int(cantidad))*cuartos
            var_subtotal = "{0:.2f}".format(subtotal)
            datos['subtotal'] = var_subtotal
            data.append(datos)
        object_cesta = Cesta.objects.filter(id_cliente=self.request.user.id).filter(id_producto__activo=True)
        context['lista_cesta'] = zip(data, object_cesta)
        total = self.calcula_total()
        context['total'] = total

        # usa pk para filtrar las subcategorías de la categoría seleccionada
        if 'pk' in self.kwargs:
            var = self.kwargs['pk']
            if var.isnumeric():
                context['subcategorias'] = SubCategoria.objects.filter(cat_id=var)
            elif not var.isnumeric():
                subcate_id = SubCategoria.objects.filter(nombre=var).values('cat_id')
                var_subcat_id = ''
                for i in subcate_id:
                    var_subcat_id = i['cat_id']
                context['subcategorias'] = SubCategoria.objects.filter(cat_id=var_subcat_id)
        return context

templates/super/base_tienda.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">
<head>
	<!-- Meta Tag -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name='copyright' content=''>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon -->
	<link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
	<!-- Web Font -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap"
	      rel="stylesheet">

	<!-- Bootstrap -->
	<link rel="stylesheet" href="{% static 'super/css/bootstrap.css' %}">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'super/css/magnific-popup.min.css' %}">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="{% static 'super/css/font-awesome.css' %}">
	<!-- Fancybox -->
	<link rel="stylesheet" href="{% static 'super/css/jquery.fancybox.min.css' %}">
	<!-- Themify Icons -->
	<link rel="stylesheet" href="{% static 'super/css/themify-icons.css' %}">
	<!-- Jquery Ui -->
	<link rel="stylesheet" href="{% static 'super/css/jquery-ui.css' %}">
	<!-- Nice Select CSS -->
	<link rel="stylesheet" href="{% static 'super/css/niceselect.css' %}">
	<!-- Animate CSS -->
	<link rel="stylesheet" href="{% static 'super/css/animate.css' %}">
	<!-- Flex Slider CSS -->
	<link rel="stylesheet" href="{% static 'super/css/flex-slider.min.css' %}">
	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'super/css/owl-carousel.css' %}">
	<!-- Slicknav -->
	<link rel="stylesheet" href="{% static 'super/css/slicknav.min.css' %}">
	<!-- Eshop StyleSheet -->
	<link rel="stylesheet" href="{% static 'super/css/reset.css' %}">
	<link rel="stylesheet" href="{% static 'css/stilo.css' %}">
	<link rel="stylesheet" href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.css' %}">
	<link rel="stylesheet" href="{% static 'super/css/responsive.css' %}">
	<!-- jquery confirm -->
	<link  rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
	<!-- style.css es para la barra de navegación, del proyecto MAXIN (podemos añadirle las librerías ASSETS) -->
	<!-- ej: menu popup en la barra de navegación -->
	<link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/miEstiloPropio.css' %}" rel="stylesheet">

	<title>famisuper</title>

	<!-- Jquery -->
	<script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
	<script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
	<script src="{% static 'super/js/jquery.min.js' %}"></script>
	<script src="{% static 'super/js/jquery-migrate-3.0.0.js' %}"></script>
	<script src="{% static 'super/js/jquery-ui.min.js' %}"></script>
	<!-- Popper JS -->
	<script src="{% static 'super/js/popper.min.js' %}"></script>
	<!-- Bootstrap JS -->
	<script src="{% static 'super/js/bootstrap.min.js' %}"></script>
	<!-- Color JS -->
	{#	<script src="{%  static 'super/js/colors.js' %}"></script>#}
	<!-- Slicknav JS -->
	<script src="{% static 'super/js/slicknav.min.js' %}"></script>
	<!-- Owl Carousel JS -->
	<script src="{% static 'super/js/owl-carousel.js' %}"></script>
	<!-- Magnific Popup JS -->
	<script src="{% static 'super/js/magnific-popup.js' %}"></script>
	<!-- Fancybox JS -->
	<script src="{% static 'super/js/facnybox.min.js' %}"></script>
	<!-- Waypoints JS -->
	<script src="{% static 'super/js/waypoints.min.js' %}"></script>
	<!-- Countdown JS -->
	<script src="{% static 'super/js/finalcountdown.min.js' %}"></script>
	<!-- Nice Select JS -->
	<script src="{% static 'super/js/nicesellect.js' %}"></script>
	<!-- Ytplayer JS -->
	<script src="{% static 'super/js/ytplayer.min.js' %}"></script>
	<!-- Flex Slider JS -->
	<script src="{% static 'super/js/flex-slider.js' %}"></script>
	<!-- ScrollUp JS -->
	<script src="{% static 'super/js/scrollup.js' %}"></script>
	<!-- Onepage Nav JS -->
	<script src="{% static 'super/js/onepage-nav.min.js' %}"></script>
	<!-- Easing JS -->
	<script src="{% static 'super/js/easing.js' %}"></script>
	<!-- Active JS -->
	<script src="{% static 'super/js/active.js' %}"></script>
	<!-- Sweetalert2 -->
	<script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
	<!-- Jquery Confirm -->
	<script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>


	{% block head %}

	{% endblock %}

</head>

	{% block content %}

	{% endblock %}


</html>

templates/super/body_tienda.html
{% extends 'super/base_tienda.html' %}
{% load static %}

{% block content %}

	<!-- incluye el header -->
	{% include 'super/header_tienda.html' %}

	{% block body %}

	{% endblock %}

<!-- incluye el footer -->
{% include 'super/footer_tienda.html' %}

{% endblock %}

templates/super/footer_tienda.html
{% load static %}

<!------ Footer ------->
<footer id="footer">
	<div class="footer-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-info">
						<h3>Famisuper</h3>
						<p>
							Calle Manuel Gonzalez Rodriguez, 14<br>
							<strong>Teléfono:</strong> 955997472<br>
							<strong>Email:</strong> famisuper@oulook.com<br>
						</p>
{#						<div class="social-links mt-3">#}
{#							<a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>#}
{#							<a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>#}
{#							<a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>#}
{#						</div>#}
					</div>
				</div>
				<div class="col-lg-2 col-md-6 footer-links">
					<h4>Links</h4>
					<ul>
						<li><i class="bx bx-chevron-right"></i> <a href="{% url 'administrador:super_lista' %}">Tienda</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="{% url 'administrador:oferta_lista' %}">Ofertas</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="{% url 'inicio' %}">Sobre nosotros</a></li>
					</ul>
				</div>
				<div class="col-lg-3 col-md-6 footer-links">
					<h4>Nuestros servicios</h4>
					<ul>
						<li><i class="bx bx-chevron-right"></i> <a>Compra sin tarjeta fácilmente</a></li>
						<li><i class="bx bx-chevron-right"></i> <a>Reparto a domicilio</a></li>
						<li><i class="bx bx-chevron-right"></i> <a>Atención personalizada</a></li>
						<li><i class="bx bx-chevron-right"></i> <a>Los mejores precios</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<br>
	<div class="container">
		<footer class="main-footer text-center" id="logo_footer">
			<a id="logo_footer">FAMISUPER</a><br>
		</footer>
	</div>
</footer>
<!-- End Footer -->

templates/super/header_tienda.html
<!--------------------------- Header -------------------------->
<header id="header" class="fixed-top d-flex align-items-center">
	<div class="container d-flex justify-content-between">

		<div class="logo">
			<h1><a href="" id="logo_sidebar">FAMISUPER</a></h1>
		</div>

		<nav id="navbar" class="navbar">
			<ul>
				<li><a class="nav-link scrollto active" href="{% url 'administrador:super_lista'%}">Tienda</a></li>
				<li><a class="nav-link scrollto" href="{% url 'administrador:muestra_oferta_lista'%}">Ofertas</a></li>
				<li>
					{% if user.is_authenticated %}
						<a class="nav-link scrollto" href="{% url 'administrador:favoritos_lista'%}">Favoritos</a>
					{% else %}
						<a class="nav-link scrollto" href="{% url 'perfil:login'%}">Favoritos</a>
					{% endif %}
				</li>

				<li>
					{% if user.is_authenticated %}
						<a class="nav-link scrollto" href="{% url 'administrador:cesta_lista' %}">Cesta</a></li>
					{% else %}
                       <a class="nav-link scrollto" href="{% url 'perfil:login' %}">Cesta</a>
                    {% endif %}
				<li>
					{% if user.is_authenticated %}
                        <a class="nav-link scrollto" href="{% url 'administrador:panel_control' %}">{{ user.username }}</a>
{#					{% elif request.user.is_authenticated %}#}
{#                        <a class="nav-link scrollto" href="{% url 'administrador:CSV' %}">{{ request.user.username }}</a>#}
                    {% else %}
                       <a class="nav-link scrollto" href="{% url 'perfil:login' %}">Iniciar Sesión</a>
                    {% endif %}
				</li>
			</ul>
			<i class="bi bi-list mobile-nav-toggle"></i>
		</nav>
		<!-- .navbar -->
	</div>
</header>
<!-- Finaliza Header -->