aplicaciones/administrador/urls.py
from django.urls import path

from .views.cesta.views import CestaListView, CestaDeleteView, CestaFacturaPdfView
from .views.categoria.views import *
from .views.clientes.views import ClienteCreateView, ClienteUpdateView, ClienteDeleteView, ClienteListView, \
    ClienteSuperCreateView, ClienteSuperUpdateView
from .views.favoritos.views import FavoritosListView, FavoritosDeleteView, FavoritosCestaCreateView
from .views.gestiona_favoritos.views import GestionaFavoritosListView
from .views.importar_csv.views import ImportarCSVListView, ImportarCSVUpdateView, ImportarCSVDeleteView
from .views.muestra_oferta.views import MuestraOfertasListView
from .views.gestiona.views import GestionaProductosListView, GestionaProductosUpdateView, GestionaProductosDeleteView, \
    GestionaProductosCreateView
from .views.ofertas.views import OfertaUpdateView, OfertaCreateView, OfertaListView, OfertaDeleteView
from .views.productos.views import ProductoListView, ProductoCreateView, ProductoUpdateView, ProductoDeleteView
from .views.subcategoria.views import SubCategoriaFormView, SubCategoriaDeleteView, SubCategoriaUpdateView, \
    SubCategoriaCreateView, SubCategoriaListView
from .views.super.views import SuperListView  # , PruebaListView,
from .views.test.views import TestView
from aplicaciones.administrador.views.panelcontrol.views import *
from aplicaciones.administrador.views.ventas.views import VentaListView, VentaCreateView, VentaDeleteView, \
    VentaUpdateView, VentaFacturaPdfView

app_name = 'administrador'

urlpatterns = [
    # categoria
    path('categoria/lista/', CategoriaListView.as_view(), name='categoria_lista'),
    path('categoria/crear/', CategoriaCreateView.as_view(), name='categoria_crear'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_editar'),
    path('categoria/eliminar/<int:pk>/', CategoriaDeleteView.as_view(), name='categoria_eliminar'),
    path('categoria/form/', CategoriaFormView.as_view(), name='categoria_form'),
    # subcategoria
    path('subcategoria/lista/', SubCategoriaListView.as_view(), name='subcategoria_lista'),
    path('subcategoria/crear/', SubCategoriaCreateView.as_view(), name='subcategoria_crear'),
    path('subcategoria/editar/<int:pk>/', SubCategoriaUpdateView.as_view(), name='subcategoria_editar'),
    path('subcategoria/eliminar/<int:pk>/', SubCategoriaDeleteView.as_view(), name='subcategoria_eliminar'),
    path('subcategoria/form/', SubCategoriaFormView.as_view(), name='subcategoria_form'),
    # clientes
    path('cliente/lista/', ClienteListView.as_view(), name='cliente_lista'),
    path('cliente/crear/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('cliente/editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editar'),
    path('cliente/eliminar/<int:pk>/', ClienteDeleteView.as_view(), name='cliente_eliminar'),
    path('cliente/crearperfil/', ClienteSuperCreateView.as_view(), name='cliente_crearSuper'),
    path('cliente/editarperfil/<int:pk>/', ClienteSuperUpdateView.as_view(), name='cliente_editarSuper'),
    # productos
    path('producto/lista/', ProductoListView.as_view(), name='producto_lista'),
    path('producto/crear/', ProductoCreateView.as_view(), name='producto_crear'),
    path('producto/editar/<int:pk>/', ProductoUpdateView.as_view(), name='producto_editar'),
    path('producto/eliminar/<int:pk>/', ProductoDeleteView.as_view(), name='producto_eliminar'),
    # oferta
    path('oferta/lista/', OfertaListView.as_view(), name='oferta_lista'),
    path('oferta/crear/', OfertaCreateView.as_view(), name='oferta_crear'),
    path('oferta/editar/<int:pk>/', OfertaUpdateView.as_view(), name='oferta_editar'),
    path('oferta/eliminar/<int:pk>/', OfertaDeleteView.as_view(), name='oferta_eliminar'),
    # ventas
    path('ventas/lista/', VentaListView.as_view(), name='venta_lista'),
    path('ventas/crear/', VentaCreateView.as_view(), name='venta_crear'),
    path('ventas/editar/<int:pk>/', VentaUpdateView.as_view(), name='venta_editar'),
    path('ventas/eliminar/<int:pk>/', VentaDeleteView.as_view(), name='venta_eliminar'),
    path('ventas/factura/pdf/<int:pk>/', VentaFacturaPdfView.as_view(), name='venta_factura'),
    # Super tienda
    path('super/lista/', SuperListView.as_view(), name='super_lista'),
    path('super/lista/<str:pk>/', SuperListView.as_view(), name='super_lista_id'),
    # Cesta tienda
    path('cesta/lista/', CestaListView.as_view(), name='cesta_lista'),
    path('cesta/eliminar/<int:pk>/', CestaDeleteView.as_view(), name='cesta_eliminar'),
    path('cesta/factura/pdf/<int:pk>/', CestaFacturaPdfView.as_view(), name='cesta_factura'),
    # muestra oferta
    path('muestraoferta/lista/', MuestraOfertasListView.as_view(), name='muestra_oferta_lista'),
    # favoritos
    path('favoritos/lista/', FavoritosListView.as_view(), name='favoritos_lista'),
    path('favoritos/eliminar/<int:pk>/', FavoritosDeleteView.as_view(), name='favoritos_eliminar'),
    path('favoritos/agregar_cesta/<int:pk>/', FavoritosCestaCreateView.as_view(), name='favoritos_agregar'),
    # gestiona favoritos
    path('gestiona_favoritos/lista/', GestionaFavoritosListView.as_view(), name='gestiona_favoritosLista'),
    # gestiona productos
    path('gestiona/lista/', GestionaProductosListView.as_view(), name='gestiona_lista'),
    path('gestiona/crear/', GestionaProductosCreateView.as_view(), name='gestiona_crear'),
    path('gestiona/editar/<int:pk>/', GestionaProductosUpdateView.as_view(), name='gestiona_editar'),
    path('gestiona/eliminar/<int:pk>/', GestionaProductosDeleteView.as_view(), name='gestiona_eliminar'),
    # Importar CSV
    path('importar/lista/', ImportarCSVListView.as_view(), name='importar_lista'),
    path('importar/editar/<int:pk>/', ImportarCSVUpdateView.as_view(), name='importar_editar'),
    path('importar/eliminar/<int:pk>/', ImportarCSVDeleteView.as_view(), name='importar_eliminar'),
    # inicio
    path('panelcontrol/', PanelControlView.as_view(), name='panel_control'),
    # test
    path('test/', TestView.as_view(), name='test'),
]

aplicaciones/login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from aplicaciones.login.views import *

app_name = 'perfil'

urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password/', ReseteoPassWordView.as_view(), name='reset_contraseña'),
    path('change/password/<str:token>/', CambiarPassWordView.as_view(), name='change_contraseña')
    # path('logout/', LogoutRedirectView.as_view(), name='logout')
]

configuracion/urls.py
"""configuracion URL Configuration

The `urlpatterns` list routes URLs to oferta. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function oferta
    1. Add an import:  from my_app import oferta
    2. Add a URL to urlpatterns:  path('', oferta.home, name='home')
Class-based oferta
    1. Add an import:  from other_app.oferta import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from aplicaciones.paginainicio.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='inicio'),                                        # página de inicio
    path('adm/', include('aplicaciones.administrador.urls')),                            # llama a tienda
    path('login/', include('aplicaciones.login.urls')),
    path('reporte/', include('aplicaciones.reportes.urls')),
    path('usuario/', include('aplicaciones.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicaciones/login/models.py
from django.db import models

# Create your models here.

aplicaciones/login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import TextInput, PasswordInput
from aplicaciones.administrador.models import Cliente
from aplicaciones.usuarios.models import Usuario


class ReseteoPassWordForm(forms.Form):

    email = forms.CharField(widget=TextInput(attrs={
        'placeholder': 'Introduzca su email',
        'class': 'form.control',
        'autocomplete': 'off'
    }))

    def clean(self):
        cleaned = super().clean()
        if not Cliente.objects.filter(email=cleaned['email']).exists():
            self._errors['error'] = self._errors.get('error ', self.error_class())
            self._errors['error'].append(' El correo electrónico no existe')
            # raise forms.ValidationError('El correo no existe')
        return cleaned

    def get_cliente(self):
        email = self.cleaned_data.get('email')
        return Usuario.objects.get(email=email)


class CambiarPassWordForm(forms.Form):
    password = forms.CharField(widget=PasswordInput(attrs={
        'placeholder': 'Introduzca su nueva contraseña',
        'class': 'form.control',
        'autocomplete': 'off'
    }))

    confirmarPassword = forms.CharField(widget=PasswordInput(attrs={
        'placeholder': 'Repita la contraseña',
        'class': 'form.control',
        'autocomplete': 'off'
    }))

    def clean(self):
        cleaned = super().clean()
        password = cleaned['password']
        confirmarPassword = cleaned['confirmarPassword']
        if password != confirmarPassword:
            self._errors['error'] = self._errors.get('error ', self.error_class())
            self._errors['error'].append('Las contraseñas deben ser iguales')
            # raise forms.ValidationError('Las contraseñas deben ser iguales')
        return cleaned

aplicaciones/login/views.py
import smtplib
import uuid

from django.template.loader import render_to_string

from aplicaciones.administrador.models import Cesta
from aplicaciones.usuarios.models import Usuario
from configuracion import settings
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, PasswordResetView
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, RedirectView
import configuracion.settings as setting
from aplicaciones.login.forms import ReseteoPassWordForm, CambiarPassWordForm


class LoginFormView(LoginView):
    template_name = 'login/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(setting.LOGIN_REDIRECT_URL)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Iniciar sesión'
        return context


class LoginFormView2(FormView):
    form_class = AuthenticationForm
    template_name = 'login/login.html'
    success_url = reverse_lazy(setting.LOGIN_REDIRECT_URL)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tiulo'] = 'Iniciar sesión'
        return context


class LogoutRedirectView(RedirectView):
    pattern_name = 'login'

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return super().dispatch(request, *args, **kwargs)


class ReseteoPassWordView(FormView):
    form_class = ReseteoPassWordForm
    template_name = 'login/resetpwd.html'
    success_url = reverse_lazy(setting.LOGIN_REDIRECT_URL)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def enviar_email_reset_password(self, user):
        data = {}
        try:
            URL = settings.DOMINIO if not settings.DEBUG else self.request.META['HTTP_HOST']

            user.token = uuid.uuid4()
            user.save()

            mailServer = smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT)
            mailServer.starttls()
            mailServer.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)

            email_to = user.email
            mensaje = MIMEMultipart()
            mensaje['From'] = settings.EMAIL_HOST_USER
            mensaje['To'] = email_to
            mensaje['Subject'] = 'Cambio de contraseña'

            context = render_to_string('login/enviar_email.html', {
                'user': user,
                'link_resetpwd': 'http://{}/login/change/password/{}/'.format(URL, str(user.token)),
                'link_home': 'http://{}'.format(URL)
            })
            mensaje.attach(MIMEText(context, 'html'))

            mailServer.sendmail(settings.EMAIL_HOST_USER,
                                email_to,
                                mensaje.as_string())

        except Exception as e:
            data['error'] = str(e)
        return data

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            form = ReseteoPassWordForm(request.POST)
            if form.is_valid():
                user = form.get_cliente()
                data = self.enviar_email_reset_password(user)
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Cambiar contraseña'
        return context


class CambiarPassWordView(FormView):
    form_class = CambiarPassWordForm
    template_name = 'login/cambiopwd.html'
    success_url = reverse_lazy(setting.LOGIN_REDIRECT_URL)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        token = self.kwargs['token']
        if Usuario.objects.filter(token=token).exists():
            return super().get(request, *args, **kwargs)
        elif not Usuario.objects.filter(token=token).exists():
            return HttpResponseRedirect('/')

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            form = CambiarPassWordForm(request.POST)
            if form.is_valid():
                usuario = Usuario.objects.get(token=self.kwargs['token'])
                usuario.set_password(request.POST['password'])
                usuario.token = uuid.uuid4()
                usuario.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Cambiar contraseña'
        context['login_url'] = settings.LOGIN_URL
        return context

aplicaciones/login/templates/login/base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{{ tiulo }}</title>
	<!-- Tell the browser to be responsive to screen width -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
	<!-- Theme style -->
	<link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
	<!-- Google Font: Source Sans Pro -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
	<!-- Sweetalert2 -->
	<script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
	<!-- jQuery -->
	<script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
	<!-- Bootstrap 4 -->
	<script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<!-- AdminLTE App -->
	<script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
	<!-- Sweetalert2 -->
	<script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
	<!-- Jquery Confirm -->
	<link  rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
	<script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
	<!-- Functions -->
	<script src="{% static 'js/functions.js' %}"></script>
	{% block head %}

	{% endblock %}

</head>
<body class="hold-transition login-page">

	{% block content %}

	{% endblock %}

</body>
</html>

aplicaciones/login/templates/login/cambiopwd.html
{% extends 'login/base.html' %}
{% load widget_tweaks %}

{% block content %}
	<div class="login-box">
		<div class="login-logo">
			<a href="{% url 'inicio' %}"><b>Famisuper</b></a>
		</div>
		<div class="card">
			<div class="card-body login-card-body">
				<p class="login-box-msg">Cambio de contraseña</p>
				<form action=".." method="post">
					<input type="hidden" name="next" value="{{ next }}">
					{% csrf_token %}
					<div class="input-group mb-3">
						{{ form.password|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Introduzca la nueva contraseña' }}
						<div class="input-group-append">
							<div class="input-group-text">
								<span class="fas fa-lock"></span>
							</div>
						</div>
					</div>
					<div class="input-group mb-3">
						{{ form.confirmarPassword|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Repita la contraseña' }}
						<div class="input-group-append">
							<div class="input-group-text">
								<span class="fas fa-lock"></span>
							</div>
						</div>
					</div>
					<hr>
					<div class="row">
						<div class="col-lg-12">
							<button type="submit" class="btn btn-primary btn-block">
								<i class="fas fa-envelope"></i>&nbsp;Enviar
							</button>
						</div>
					</div>
					<p class="text-center mt-2">
						Si deseas regresar a Famisuper pulse
							<a href="{% url 'perfil:reset_contraseña' %}"> aquí</a>
					</p>
				</form>
			</div>
		</div>
		<script type="application/javascript">
            $(function () {
                $('form').on('submit', function (e) {
                    e.preventDefault();
                    let parameters = new FormData(this);
                    submit_with_ajax(window.location.pathname, 'Notificación', '¿Está seguro de cambiar su contraseña?', parameters, function () {
                        Swal.fire({
                            title: 'Notificación',
                            text: 'Su contraseña ha sido cambiada correctamente',
                            icon: 'success',
                            timer: 5000,
                            onClose: () => {
                                location.href = '{{ login_url }}';
                            }
                        }).then((result) => {

                        });
                    });
                });
            });
		</script>
	</div>
{% endblock %}

aplicaciones/login/templates/login/login.html
{% extends 'login/base.html' %}
{% load widget_tweaks %}

{% block content %}
	<div class="login-box">
	<div class="login-logo">
		<a href="{% url 'inicio' %}"><b>Famisuper</b></a>
	</div>
	<div class="card">
		<div class="card-body login-card-body">
			<p class="login-box-msg">Inicie sesión con sus credenciales</p>
			<form action="." method="post">
				<input type="hidden" name="next" value="{{ next }}">
				{% csrf_token %}
				<div class="input-group mb-3">
					{{ form.username|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Introduzca su nombre de usuario' }}
					<div class="input-group-append">
						<div class="input-group-text">
							<span class="fas fa-envelope"></span>
						</div>
					</div>
				</div>
				<div class="input-group mb-3">
					{{ form.password|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Introduzca su contraseña' }}
					<div class="input-group-append">
						<div class="input-group-text">
							<span class="fas fa-lock"></span>
						</div>
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-lg-12">
						<button type="submit" class="btn btn-primary btn-block">
							<i class="fas fa-sign-in-alt"></i> Iniciar sesión
						</button>
					</div>
				</div>
				<br>
				<div class="col-lg-12">
					<p>
						<a href="{% url 'administrador:cliente_crearSuper' %}" class="text-center">
							Registrar nuevo usuario
						</a>
					</p>
					<p>
						<a href="{% url 'perfil:reset_contraseña' %}">
							¿Olvidaste la contraseña?
						</a>
					</p>
				</div>
			</form>
		</div>
	</div>
	<script type="application/javascript">
        {% if form.errors %}
            let errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}
	</script>
</div>
{% endblock %}

aplicaciones/login/templates/login/resetpwd.html
{% extends 'login/base.html' %}
{% load widget_tweaks %}

{% block content %}
	<div class="login-box">
		<div class="login-logo">
			<a href="{% url 'inicio' %}"><b>Famisuper</b></a>
		</div>
		<div class="card">
			<div class="card-body login-card-body">
				<p class="login-box-msg">Cambiar contraseña</p>
				<form action=".." method="post">
					<input type="hidden" name="next" value="{{ next }}">
					{% csrf_token %}
					<div class="input-group mb-3">
						{{ form.email|add_class:'form-control'|attr:'autocomplete:off'|attr:'placeholder:Introduzca su correo electrónico' }}
						<div class="input-group-append">
							<div class="input-group-text">
								<span class="fas fa-envelope"></span>
							</div>
						</div>
					</div>
					<hr>
					<div class="row">
						<div class="col-lg-12">
							<button type="submit" class="btn btn-primary btn-block">
								<i class="fas fa-envelope"></i>&nbsp;Enviar
							</button>
						</div>
					</div>
					<p class="text-center mt-2">
						Si deseas regresar a Famisuper pulse
							<a href="{% url 'inicio' %}"> aquí</a>
					</p>
				</form>
			</div>
		</div>
		<script type="application/javascript">
            $(function () {
                $('form').on('submit', function (e) {
                    e.preventDefault();
                    let parameters = new FormData(this);
                    submit_with_ajax(window.location.pathname, 'Notificación', '¿Confirmar la nueva contraseña?', parameters, function () {
                        Swal.fire({
                            title: 'Notificación',
                            text: 'Se ha enviado un correo electrónico con los pasos a seguir para que pueda cambiar su contraseña',
                            icon: 'success',
                            timer: 5000,
                            onClose: () => {
                                location.href = '/';
                            }
                        }).then((result) => {

                        });
                    });
                });
            });
		</script>
	</div>
{% endblock %}